### ISSUE TITLE
Make family names searchable in PR titles

### ISSUE THREAD

**Issue by davelab6** [m4rc1e/gf-hotfix#1]
https://github.com/google/fonts/pulls?utf8=%E2%9C%93&q=is%3Apr%20alegreya should return more than just that 1 hotfix, eg https://github.com/google/fonts/pulls?utf8=%E2%9C%93&q=is%3Apr%20alegreyasc

**Comment by davelab6** [comment]
If your hot fix tools have finished their useful life, u guess there's no reason to fix this issue

**Comment by m4rc1e** [comment]
Agreed.
