### ISSUE TITLE
Don't include \r and \n

### ISSUE THREAD

**Issue by davelab6** [m4rc1e/gf-hotfix#2]
https://github.com/google/fonts/pull/940 was a problem in production :) Place replace linebreaks with a space unless they have spaces before or after that would results in a double space; then just remove.

**Comment by m4rc1e** [comment]
Ok, we have a few of these I'll need to sort. I'll do that now.

**Comment by m4rc1e** [comment]
They're all gone :-)

Every hotfix family which introduced this error in the first pr now has a second pr to fix it. 

For example:
https://github.com/google/fonts/pull/800/commits
